version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  
  php:
    image: poc_php
    build:
      context: ./app
      dockerfile: ./docker/php-fpm/Dockerfile
      target: dev
      args:
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST:-172.17.0.1} # No Mac, substituir por: host.docker.internal
        - DB_SERVER=database
        - DB_PORT=3306
        - DB_NAME=symfony_docker
        - DB_USER=symfony
        - DB_PASSWORD=symfony
        - INFRA_ENVIRONMENT=dev
        - APP_ENV=dev
    environment:
      DATABASE_URL: mysql://symfony:symfony@database:3306/symfony_docker?serverVersion=8
    ports:
      - '9000:9000'
    volumes:
      - ./app:/app
      - ./app/docker/php-fpm/php.dev.ini:/usr/local/etc/php/conf.d/extras-php.ini
    depends_on:
      - database
  
  nginx:
    image: poc_nginx
    links:
      - php
    build:
      context: ./app
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - "./app/public:/var/www/app/public"
    depends_on:
      - php
      - database
    environment:
      - API_HOST=php
      - API_PORT=9000