version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  
  php:
    container_name: php
    build:
      context: ./php
    environment:
      DATABASE_URL: mysql://symfony:symfony@database:3306/symfony_docker?serverVersion=8
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    environment:
      - API_HOST=php
      - API_PORT=9000